context:
  version: "12.6.0"

package:
  name: cucumber-js
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@cucumber/cucumber/-/cucumber-${{ version }}.tgz
  sha256: cf704132eda21173efd8e7590e8d2ebedd95240292e43a044f750b7c05e71656

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cucumber-js --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The official JavaScript implementation of Cucumber.
  homepage: https://github.com/cucumber/cucumber-js
  repository: https://github.com/cucumber/cucumber-js

extra:
  recipe-maintainers:
    - danielnachun
