context:
  version: "12.8.2"

package:
  name: cucumber-js
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@cucumber/cucumber/-/cucumber-${{ version }}.tgz
  sha256: 6062d02ea25c89374e60c1f734c0d7789eb987a04869f2b906d1526768b4b28b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cucumber-js --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The official JavaScript implementation of Cucumber.
  homepage: https://github.com/cucumber/cucumber-js
  repository: https://github.com/cucumber/cucumber-js

extra:
  recipe-maintainers:
    - danielnachun
