context:
  version: "12.7.0"

package:
  name: cucumber-js
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@cucumber/cucumber/-/cucumber-${{ version }}.tgz
  sha256: 77c150325204efd26463d0e446a9d979f29f9830613484a642eb40b4d23f3b70

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cucumber-js --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The official JavaScript implementation of Cucumber.
  homepage: https://github.com/cucumber/cucumber-js
  repository: https://github.com/cucumber/cucumber-js

extra:
  recipe-maintainers:
    - danielnachun
