context:
  version: "13.3.0"

package:
  name: cucumber-js
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@cucumber/cucumber/-/cucumber-${{ version }}.tgz
  sha256: f2d31173044ae61e9b3015c834bca3fc9198340a5877747c13aa555b9ce2857e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cucumber-js --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The official JavaScript implementation of Cucumber.
  homepage: https://github.com/cucumber/cucumber-js
  repository: https://github.com/cucumber/cucumber-js

extra:
  recipe-maintainers:
    - danielnachun
