context:
  version: "12.8.0"

package:
  name: cucumber-js
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@cucumber/cucumber/-/cucumber-${{ version }}.tgz
  sha256: d40aa7c3af23a8df3fb190aafa6b054e51a110725e93ced67f1bc588526489cb

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cucumber-js --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The official JavaScript implementation of Cucumber.
  homepage: https://github.com/cucumber/cucumber-js
  repository: https://github.com/cucumber/cucumber-js

extra:
  recipe-maintainers:
    - danielnachun
